name: Python Tests

on:
  push:
    branches:
      - '**'        # Run tests on all branches

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v4  # Updated to v4 for Node.js 20 compatibility

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5  # Updated to v5 for Node.js 20 compatibility
        with:
          python-version: 3.9

      # Step 3: Run unittest
      - name: Run tests
        run: python -m unittest discover -s tests
