name: Python Tests

on:
  push:
    branches:
      - '**'        # Run tests on all branches

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9  # Replace with your desired Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy

      # Step 4: Run unittest
      - name: Run tests
        run: python -m unittest discover -s tests
